WebLayihe/WebLayihe/Models/BlogCatagory.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace WebLayihe.Models
{
    public class BlogCatagory
    {
        public int Id { get; set; }

        [MaxLength(30)]
        [Required]
        public string Name { get; set; }

        public List<Blog> Blogs { get; set; }

    }
}

WebLayihe/WebLayihe/Areas/Admin/Controllers/BlogCatagoryController.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebLayihe.DAL;
using WebLayihe.Models;

namespace WebLayihe.Areas.Admin.Controllers
{
    public class BlogCatagoryController : Controller
    {
        // GET: Admin/BlogCatagory

        // CRUD blog Catagories

        EduHomeContex db = new EduHomeContex();
        public ActionResult Index()
        {
            if (Session["Admin"] != null)
            {
            List<BlogCatagory> blogCatagories = db.BlogCatagories.ToList();
            return View(blogCatagories);
            }
            return RedirectToAction("Login", "RegisterAdmin");


        
        }

        public ActionResult Create()
        {
            if (Session["Admin"] != null)
            {
              return View();
           
            }
            return RedirectToAction("Login", "RegisterAdmin");



        }


        [HttpPost]
        public ActionResult Create(BlogCatagory blogCatagory )
        {
            if (ModelState.IsValid)
            {
                db.BlogCatagories.Add(blogCatagory);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(blogCatagory);
        }

        public ActionResult Update(int id)
        {
            if (Session["Admin"] != null)
            {
            BlogCatagory blogCatagory = db.BlogCatagories.Find(id);
            if (blogCatagory==null)
            {
                return HttpNotFound();
            }
            return View(blogCatagory);
            }
            return RedirectToAction("Login", "RegisterAdmin");




        }

        [HttpPost]
        public ActionResult Update(BlogCatagory blogCatagory)
        {
            if (ModelState.IsValid)
            {
                db.Entry(blogCatagory).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(blogCatagory); 
        }

        public ActionResult Delete(int id)
        {
            if (Session["Admin"] != null)
            {
            BlogCatagory blogCatagory = db.BlogCatagories.Find(id);
            if (blogCatagory==null)
            {
                return HttpNotFound();
            }
            db.BlogCatagories.Remove(blogCatagory);
            db.SaveChanges();
            return RedirectToAction("index");
            }
            return RedirectToAction("Login", "RegisterAdmin");





        }

    }
}

WebLayihe/WebLayihe/Areas/Admin/Views/BlogCatagory/Create.cshtml
@model WebLayihe.Models.BlogCatagory

@{
    ViewBag.Title = "Create";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

<h2>Create</h2>

@*Create of Blog Catagory*@

<form   method="post">

    <div class="form-horizontal">
        <h4>BlogCatagory</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </div>
    </div>
</form>


<div>
    @Html.ActionLink("Back to List", "Index")
</div>

WebLayihe/WebLayihe/Areas/Admin/Views/BlogCatagory/Index.cshtml
@model IEnumerable<WebLayihe.Models.BlogCatagory>

@{
    ViewBag.Title = "Index";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

<h2>Index</h2>

@*index of Blog Catagory*@

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Name)
        </td>
        <td>
            @Html.ActionLink("Edit", "Update", new { id=item.Id }) |
            <a href="@Url.Action("Delete", "BlogCatagory", new { id=item.Id })" onclick="return confirm('are you Sure ??')">Delete</a>
        </td>
    </tr>
}

</table>

WebLayihe/WebLayihe/Areas/Admin/Views/BlogCatagory/Update.cshtml
@model WebLayihe.Models.BlogCatagory

@{
    ViewBag.Title = "Update";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

<h2>Update</h2>

@*update of Blog catagory*@

<form method="post">

 
    <div class="form-horizontal">
        <h4>BlogCatagory</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Update" class="btn btn-primary" />
            </div>
        </div>
    </div>
</form>


<div>
    @Html.ActionLink("Back to List", "Index")
</div>