WebLayihe/WebLayihe/Models/Subscribe.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace WebLayihe.Models
{
    public class Subscribe
    {
        public int Id { get; set; }

        [MaxLength(30)]
        [Required]
        public string Email { get; set; }

        public DateTime AddedDate { get; set; }
    }
}

WebLayihe/WebLayihe/Areas/Admin/Controllers/SubscribeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebLayihe.DAL;
using WebLayihe.Models;

namespace WebLayihe.Areas.Admin.Controllers
{
    public class SubscribeController : Controller
    {
        // GET: Admin/Subscribe

        //READ Subscribe
        EduHomeContex db = new EduHomeContex();
        public ActionResult Index()
        {
            if (Session["Admin"] != null)
            {
            List<Subscribe> subscribes = db.Subscribes.ToList();
            return View(subscribes);
            }
            return RedirectToAction("Login", "RegisterAdmin");



        }


        public ActionResult Delete(int id)
        {
            Subscribe subscribe = db.Subscribes.Find(id);
            if (subscribe==null)
            {
                return HttpNotFound();
            }
            db.Subscribes.Remove(subscribe);
            db.SaveChanges();
            return RedirectToAction("Index");
        }


    }
}

WebLayihe/WebLayihe/Areas/Admin/Views/Subscribe/Index.cshtml
@model IEnumerable<WebLayihe.Models.Subscribe>

@{
    ViewBag.Title = "Index";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

<h2>Index</h2>
<h2>
    Subscribes
</h2>


<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Email)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.AddedDate)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Email)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.AddedDate)
            </td>
            <td>
                <a href="@Url.Action("Delete", "Subscribe", new { id=item.Id })" onclick="return confirm('are you sure ?')">Delete</a>
            </td>
        </tr>
    }

</table>