WebLayihe/WebLayihe/Models/AboutSlide.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace WebLayihe.Models
{
    public class AboutSlide
    {
        public int Id { get; set; }

        [MaxLength(40)]
        [Required]
        public string Fullname { get; set; }

        [MaxLength(300)]
        [Required]
        public string Content { get; set; }

        [MaxLength(200)]
        public string Image { get; set; }

        [NotMapped]
        public HttpPostedFileBase ImageFile { get; set; }

        public int OccupationId { get; set; }

        public Occupation Occupation { get; set; }
    }
}

WebLayihe/WebLayihe/Areas/Admin/Controllers/AboutSlideController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebLayihe.DAL;
using WebLayihe.Models;

namespace WebLayihe.Areas.Admin.Controllers
{
    public class AboutSlideController : Controller
    {
        // GET: Admin/AboutSlide

        // CRUD About Slider

        EduHomeContex db = new EduHomeContex();

        public ActionResult Index()
        {

            if (Session["Admin"] != null)
            {
                   List<AboutSlide> aboutSlides = db.AboutSlides.Include("Occupation").ToList();
                 return View(aboutSlides);
            }
            return RedirectToAction("Login", "RegisterAdmin");

            
        }


        public ActionResult Create()
        {
            if (Session["Admin"] != null)
            {
                
            ViewBag.Occupations = db.Occupations.ToList();
            return View();
            }
            return RedirectToAction("Login", "RegisterAdmin");

            
        }

        [HttpPost]
        public ActionResult Create(AboutSlide aboutSlide)
        {

            if (aboutSlide.OccupationId<1)
            {
                ModelState.AddModelError("", "occupation is required");
                ViewBag.Occupations = db.Occupations.ToList();
                return View(aboutSlide);
            }
            if (ModelState.IsValid)
            {
                if (aboutSlide.ImageFile==null)
                {
                    ModelState.AddModelError("ImageFile", "image is requred");
                    ViewBag.Occupations = db.Occupations.ToList();
                    return View(aboutSlide);
                }
                else
                {
                    string imageName = DateTime.Now.ToString("ddMMyyyyHHmmssfff") + aboutSlide.ImageFile.FileName;
                    string imagePath = Path.Combine(Server.MapPath("~/Uploads/"), imageName);

                    aboutSlide.ImageFile.SaveAs(imagePath);
                    aboutSlide.Image = imageName;
                }

                db.AboutSlides.Add(aboutSlide);
                db.SaveChanges();

                return RedirectToAction("Index");
            }

            ViewBag.Occupations = db.Occupations.ToList();
            return View();
        }

        public ActionResult Update(int id)
        {

            if (Session["Admin"] != null)
            {
         AboutSlide aboutSlide = db.AboutSlides.Find(id);
                    if (aboutSlide==null)
                    {
                        return HttpNotFound();
                    }
                    ViewBag.Occupations = db.Occupations.ToList();
                    return View(aboutSlide);
            }
            return RedirectToAction("Login", "RegisterAdmin");


           
        }

        [HttpPost]
        public ActionResult Update(AboutSlide aboutSlide)
        {
            AboutSlide AboutSlide = db.AboutSlides.Find(aboutSlide.Id);

            if (aboutSlide.OccupationId < 1)
            {
                ModelState.AddModelError("", "occupation is required");
                ViewBag.Occupations = db.Occupations.ToList();
                return View(AboutSlide);
            }
            if (ModelState.IsValid)
            {
                if (aboutSlide.ImageFile != null)
                {
                    string imageName = DateTime.Now.ToString("ddMMyyyyHHmmssfff") + aboutSlide.ImageFile.FileName;
                    string imagePath = Path.Combine(Server.MapPath("~/Uploads/"), imageName);

                    string oldImagePath = Path.Combine(Server.MapPath("~/Uploads/"), AboutSlide.Image);
                    System.IO.File.Delete(oldImagePath);

                    aboutSlide.ImageFile.SaveAs(imagePath);
                    AboutSlide.Image = imageName;
                }

                AboutSlide.Fullname = aboutSlide.Fullname;
                AboutSlide.Content = aboutSlide.Content;
                AboutSlide.OccupationId = aboutSlide.OccupationId;

                db.Entry(AboutSlide).State = EntityState.Modified;
                db.SaveChanges();

                return RedirectToAction("Index");
            }

            ViewBag.Occupations = db.Occupations.ToList();
            return View(AboutSlide);
        }


        public ActionResult Delete(int id)
        {
            if (Session["Admin"] != null)
            {
                AboutSlide aboutSlide = db.AboutSlides.Find(id);
                if (aboutSlide== null)
                {
                    return HttpNotFound();
                }
                db.AboutSlides.Remove(aboutSlide);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return RedirectToAction("Login", "RegisterAdmin");



        }

    }
}

WebLayihe/WebLayihe/Areas/Admin/Views/AboutSlide/Create.cshtml
@model WebLayihe.Models.AboutSlide

@{
    ViewBag.Title = "Create";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

<h2>Create</h2>

<form enctype="multipart/form-data" method="post">

    <div class="form-horizontal">
        <h4>AboutSlide</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Fullname, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Fullname, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Fullname, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Content, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Content, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Content, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ImageFile, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.ImageFile, new { @class = "form-control", @type = "file" })
                @Html.ValidationMessageFor(model => model.ImageFile, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-10">
                <label>Occupation</label>
                <select class="form-control" name="OccupationId">
                    <option value="value">Choose</option>
                    @foreach (var item in ViewBag.Occupations)
                    {
                        <option value="@item.Id">@item.Name</option>
                    }
                </select>
            </div>
        </div>


        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </div>
    </div>
</form>


<div>
    @Html.ActionLink("Back to List", "Index")
</div>

WebLayihe/WebLayihe/Areas/Admin/Views/AboutSlide/Index.cshtml
@model IEnumerable<WebLayihe.Models.AboutSlide>

@{
    ViewBag.Title = "Index";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Fullname)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Content)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Image)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.OccupationId)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Fullname)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Content)
        </td>
        <td>
            <img src="~/Uploads/@item.Image" alt="image" width="120" />
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Occupation.Name)
        </td>
        <td>
            @Html.ActionLink("Edit", "Update", new { id=item.Id }) |
            <a href="@Url.Action("Delete", "AboutSlide", new { id=item.Id })" onclick="return confirm('ARE you Sure ?')">Delete</a>
        </td>
    </tr>
}

</table>

WebLayihe/WebLayihe/Areas/Admin/Views/AboutSlide/Update.cshtml
@model WebLayihe.Models.AboutSlide

@{
    ViewBag.Title = "Update";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

<h2>Update</h2>

<form method="post" enctype="multipart/form-data">

    <div class="form-horizontal">
        <h4>AboutSlide</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Fullname, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Fullname, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Fullname, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Content, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Content, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Content, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ImageFile, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <img src="~/Uploads/@Model.Image" alt="image" width="130" />
                @Html.TextBoxFor(model => model.ImageFile, new { @class = "form-control", @type = "file" })
                @Html.ValidationMessageFor(model => model.ImageFile, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-10">
                <label>Occupation</label>
                <select class="form-control" name="OccupationId">
                    <option value="value">Choose</option>
                    @foreach (var item in ViewBag.Occupations)
                    {
                        <option value="@item.Id" @(Model.OccupationId == item.Id ? "selected" : "")>@item.Name</option>
                    }
                </select>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </div>
    </div>
</form>

<div>
    @Html.ActionLink("Back to List", "Index")
</div>