WebLayihe/WebLayihe/Models/Header.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace WebLayihe.Models
{
    public class Header
    {
        public int Id { get; set; }

        [MaxLength(150)]
        [Required]
        public string Title { get; set; }
        
        [MaxLength(200)]
        public string Image { get; set; }

        [NotMapped]
        public HttpPostedFileBase ImageFile { get; set; }

        [MaxLength(50)]
        [Required]
        public string Page { get; set; }
    }
}

WebLayihe/WebLayihe/Areas/Admin/Controllers/HeaderController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebLayihe.DAL;
using WebLayihe.Models;

namespace WebLayihe.Areas.Admin.Controllers
{
    public class HeaderController : Controller
    {
        // GET: Admin/Header
        // CRUD Heders
        EduHomeContex db = new EduHomeContex();
        public ActionResult Index()
        {
            if (Session["Admin"] != null)
            {
            List<Header> headers = db.Headers.ToList();
            return View(headers);
            }
            return RedirectToAction("Login", "RegisterAdmin");



        }


        public ActionResult Create()
        {
            return View();
        }


        [HttpPost]
        public ActionResult Create(Header header)
        {
            if (ModelState.IsValid)
            {
                if (header.ImageFile == null)
                {
                    ModelState.AddModelError("ImageFile", "image is requred");
                    return View();
                }
                else
                {
                    string imageName = DateTime.Now.ToString("ddMMyyyyHHmmssfff") + header.ImageFile.FileName;
                    string imagePath = Path.Combine(Server.MapPath("~/Uploads/"), imageName);

                    header.ImageFile.SaveAs(imagePath);
                    header.Image = imageName;
                }
                db.Headers.Add(header);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View();
        }


        public ActionResult Update(int id)
        {
            Header header = db.Headers.Find(id);
            if (header == null)
            {
                return HttpNotFound();
            }
            return View(header);
        }


        [HttpPost]
        public ActionResult Update(Header header)
        {
            Header Header = db.Headers.Find(header.Id);

            if (ModelState.IsValid)
            {
                if (header.ImageFile != null)
                {
                    string imageName = DateTime.Now.ToString("ddMMyyyyHHmmssfff") + header.ImageFile.FileName;
                    string imagePath = Path.Combine(Server.MapPath("~/Uploads/"), imageName);

                    string oldImagePath = Path.Combine(Server.MapPath("~/Uploads/"), Header.Image);
                    System.IO.File.Delete(oldImagePath);

                    header.ImageFile.SaveAs(imagePath);
                    Header.Image = imageName;
                }

                Header.Title = header.Title;
                Header.Page = header.Page;

                db.Entry(Header).State = EntityState.Modified;
                db.SaveChanges();

                return RedirectToAction("Index");
            }
            return View(Header);
        }

        public ActionResult Delete(int id)
        {
            Header header = db.Headers.Find(id);
            if (header==null)
            {
                return HttpNotFound();
            }
            db.Headers.Remove(header);
            db.SaveChanges();
            return RedirectToAction("Index");
        }





    }
}

WebLayihe/WebLayihe/Areas/Admin/Views/Header/Create.cshtml
@model WebLayihe.Models.Header

@{
    ViewBag.Title = "Create";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

<h2>Create</h2>

<form  method="post" enctype="multipart/form-data">


    <div class="form-horizontal">
        <h4>Header</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ImageFile, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.ImageFile, new { @class = "form-control" , @type="file" })
                @Html.ValidationMessageFor(model => model.ImageFile, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Page, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Page, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Page, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </div>
    </div>
</form>


<div>
    @Html.ActionLink("Back to List", "Index")
</div>

WebLayihe/WebLayihe/Areas/Admin/Views/Header/Index.cshtml
@model IEnumerable<WebLayihe.Models.Header>

@{
    ViewBag.Title = "Index";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Title)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Image)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Page)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Title)
        </td>
        <td>
            <img src="~/Uploads/@item.Image" alt="image heder" width="138" />
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Page)
        </td>
        <td>
            @Html.ActionLink("Edit", "Update", new { id=item.Id }) |
            <a href="@Url.Action("Delete", "Header", new { id=item.Id })" onclick="return confirm('ARE u SURE ?')">Delete</a>
        </td>
    </tr>
}

</table>

WebLayihe/WebLayihe/Areas/Admin/Views/Header/Update.cshtml
@model WebLayihe.Models.Header

@{
    ViewBag.Title = "Update";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

<h2>Update</h2>

<form  method="post" enctype="multipart/form-data">

    <div class="form-horizontal">
        <h4>Header</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ImageFile, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.ImageFile, new { @class = "form-control" , @type="file" })
                @Html.ValidationMessageFor(model => model.ImageFile, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Page, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Page, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Page, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Update" class="btn btn-primary" />
            </div>
        </div>
    </div>
</form>


<div>
    @Html.ActionLink("Back to List", "Index")
</div>